In [372]:
import pandas as pd
import os
import time
import requests

In [373]:
istat_csv = 'istat_dataset.csv'
url = 'https://esploradati.istat.it/SDMXWS/rest/data/41_983'
headers =  {'Accept': 'application/vnd.sdmx.data+csv;version=1.0.0'}
if os.path.exists(istat_csv):
    istat_df = pd.read_csv(istat_csv, dtype={"REF_AREA": str})
else:
    counter= 0 
    while counter < 5:
        try:
            response = requests.get(url, headers=headers)
            response.raise_for_status()
            with open(istat_csv, 'w', encoding='utf-8') as file:
                file.write(response.text)
            istat_df = pd.read_csv(istat_csv, dtype={"REF_AREA": str})
            print(f"Data saved to {istat_csv}")
            break
        except requests.exceptions.RequestException as error:
            print(f"Error: {error}")
            counter = counter + 1
            time.sleep(20)
            if counter == 5:
                raise Exception("Fetching data failed")

In [374]:
istat_df.shape

(573552, 16)

In [375]:
istat_df.head(5)

,DATAFLOW,FREQ,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,OBS_STATUS,NOTE_DS,NOTE_REF_AREA,NOTE_DATA_TYPE,NOTE_RESULT,NOTE_TIME_PERIOD,BASE_PER,UNIT_MEAS,UNIT_MULT
0,IT1:41_983(1.0),A,001001,KILLINJ,F,2001,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IT1:41_983(1.0),A,001001,KILLINJ,F,2002,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IT1:41_983(1.0),A,001001,KILLINJ,F,2003,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IT1:41_983(1.0),A,001001,KILLINJ,F,2004,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IT1:41_983(1.0),A,001001,KILLINJ,F,2005,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [376]:
istat_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 573552 entries, 0 to 573551
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   DATAFLOW          573552 non-null  str
 1   FREQ              573552 non-null  str
 2   REF_AREA          573552 non-null  str
 3   DATA_TYPE         573552 non-null  str
 4   RESULT            573552 non-null  str
 5   TIME_PERIOD       573552 non-null  int64
 6   OBS_VALUE         573552 non-null  int64
 7   OBS_STATUS        0 non-null       float64
 8   NOTE_DS           0 non-null       float64
 9   NOTE_REF_AREA     0 non-null       float64
 10  NOTE_DATA_TYPE    0 non-null       float64
 11  NOTE_RESULT       0 non-null       float64
 12  NOTE_TIME_PERIOD  0 non-null       float64
 13  BASE_PER          0 non-null       float64
 14  UNIT_MEAS         0 non-null       float64
 15  UNIT_MULT         0 non-null       float64
dtypes: float64(9), int64(2), str(5)
memory usage: 70.0 MB

In [377]:
istat_df['TIME_PERIOD'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
       2023, 2024])

In [378]:
df_list = []
csv_files= ['situas_2018.csv', 'situas_2019.csv', 'situas_2020.csv', 'situas_2021.csv', 'situas_2022.csv', 'situas_2023.csv', 'situas_2024.csv']
for file in csv_files:
    df_list.append(pd.read_csv(file, sep =';', decimal =',', dtype={"Codice Comune (alfanumerico)": str}))
situas_df = pd.concat(df_list, ignore_index=True)
situas_df['Superficie (Kmq)'] = situas_df['Superficie (Kmq)'].str.replace('.', '', regex=False).str.replace(',', '.', regex=False).astype(float)
situas_df.to_csv("situas_dataset.csv", index=False)
situas_df.sample(5)

,Codice Ripartizione geografica,Codice Regione,Codice Provincia (Storico),Codice Provincia/Uts,Codice Comune (alfanumerico),Codice Comune (numerico),Comune,Comune (dizione straniera),Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente)
12147,3,9,46,46,046021,46021,Montecarlo,NaN,LU,0,0,4454,2011,15.6300,2019,4400,2019
10730,2,4,22,22,022021,22021,Bondone,NaN,TN,0,0,668,2011,19.1849,2019,660,2019
38165,4,18,80,280,080062,80062,Portigliola,NaN,RC,0,0,1091,2021,5.9980,2022,1075,2022
1084,1,2,7,7,007042,7042,Lillianes,NaN,AO,0,0,465,2011,18.5463,2018,449,2018
51331,2,8,37,237,037027,37027,Gaggio Montano,NaN,BO,0,0,4797,2021,58.6697,2024,4884,2024

In [379]:
situas_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55375 entries, 0 to 55374
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Codice Ripartizione geografica  55375 non-null  int64
 1   Codice Regione                  55375 non-null  int64
 2   Codice Provincia (Storico)      55375 non-null  int64
 3   Codice Provincia/Uts            55375 non-null  int64
 4   Codice Comune (alfanumerico)    55375 non-null  str
 5   Codice Comune (numerico)        55375 non-null  int64
 6   Comune                          55368 non-null  str
 7   Comune (dizione straniera)      868 non-null    str
 8   Sigla automobilistica           54731 non-null  str
 9   Capoluogo di Provincia/Uts      55375 non-null  int64
 10  Capoluogo di Regione            55375 non-null  int64
 11  Popolazione legale              55375 non-null  int64
 12  Anno Censimento                 55375 non-null  int64
 13  Superficie (Kmq)                55375 non-null  float64
 14  Anno (Superficie)               55375 non-null  int64
 15  Popolazione residente           55375 non-null  int64
 16  Anno (Popolazione residente)    55375 non-null  int64
dtypes: float64(1), int64(12), str(4)
memory usage: 7.2 MB

In [380]:
situas_df['Superficie (Kmq)'].dtype

dtype('float64')

In [381]:
situas_df['Superficie (Kmq)'].unique()

array([13.1462, 15.7393, 46.3315, ..., 23.6116, 82.4354, 26.8906],
      shape=(12534,))

In [382]:
situas_df['Codice Comune (alfanumerico)'].head()

0    001001
1    001002
2    001003
3    001004
4    001005
Name: Codice Comune (alfanumerico), dtype: str

In [383]:
istat_df['REF_AREA'].head()

0    001001
1    001001
2    001001
3    001001
4    001001
Name: REF_AREA, dtype: str

In [384]:
# Exploring the possible values of DATA_TYPE column to understand its meaning
istat_df['DATA_TYPE'].unique()

<StringArray>
['KILLINJ', 'ROADACC']
Length: 2, dtype: str

In [385]:
# Checking basic statistics of OBS_VALUE columns to confirm that it is actually a count
istat_df['OBS_VALUE'].describe()

count    573552.000000
mean         20.207603
std         245.813966
min           0.000000
25%           0.000000
50%           1.000000
75%           8.000000
max       30254.000000
Name: OBS_VALUE, dtype: float64

In [386]:
# Checking the unit of measurement to confirm OBS_VALUE represents counts
istat_df['UNIT_MEAS'].unique()

array([nan])

In [387]:
# Checking the unit multiplier
#Both UNIT_MEAS and UNIT_MULT are NaN, so OBS_VALUE represents counts
istat_df['UNIT_MULT'].unique()

array([nan])

In [388]:
# Check which distinct codes exist in the RESULT column
istat_df['RESULT'].unique()

<StringArray>
['F', 'M', '9']
Length: 3, dtype: str

In [389]:
# Verifying KILLINJ data for a single municipality/year: 

df_killinj_test = istat_df[(istat_df['DATA_TYPE'] == 'KILLINJ') & (istat_df['TIME_PERIOD'] == 2019) & (istat_df['REF_AREA'] == '001001')]
print(df_killinj_test[['RESULT', 'OBS_VALUE']])

   RESULT  OBS_VALUE
18      F          5
42      M          0

In [390]:
# Confirming that across all municipalities KILLINJ only contain F (injured) or M (killed)
f_m_result = istat_df[(istat_df['DATA_TYPE'] == 'KILLINJ') & (istat_df['TIME_PERIOD'] == 2019)].groupby('REF_AREA')['RESULT'].unique()
print(f_m_result)

REF_AREA
001001    [F, M]
001002    [F, M]
001003    [F, M]
001004    [F, M]
001006    [F, M]
           ...
111103    [F, M]
111104    [F, M]
111105    [F, M]
111106    [F, M]
111107    [F, M]
Name: RESULT, Length: 7915, dtype: object

In [391]:
# Verifying ROADACC data for a single municipality/year: 

df_roadacc_test = istat_df[(istat_df['DATA_TYPE'] == 'ROADACC') & (istat_df['TIME_PERIOD'] == 2019) & (istat_df['REF_AREA'] == '001001')]
print(df_roadacc_test [['RESULT', 'OBS_VALUE']])

   RESULT  OBS_VALUE
66      9          3

In [392]:
#Confirming that across all municipalities ROADACC is always 9 
nine_values = istat_df[(istat_df['DATA_TYPE'] == 'ROADACC') & (istat_df['TIME_PERIOD'] == 2019)].groupby('REF_AREA')['RESULT'].unique()
print(nine_values)

REF_AREA
001001    [9]
001002    [9]
001003    [9]
001004    [9]
001006    [9]
         ...
111103    [9]
111104    [9]
111105    [9]
111106    [9]
111107    [9]
Name: RESULT, Length: 7915, dtype: object

##  OBS_VALUE, RESULT AND DATA_TYPE


**OBS_VALUE** was confirmed to be a numeric count (of injured, killed people or road accidents) based on:
-  dtype being `int64` (confirmed via `.info()`), meaning whole numbers with no decimals 
- `.describe()` showing whole numbers with and a reasonable range and no decimals (except for mean and std which is expected)
- `UNIT_MEAS` and `UNIT_MULT` both being NaN, meaning no unit conversion or
  scaling is needed before summing the values

This confirms that `OBS_VALUE` can be directly summed or compared across rows

**RESULT** was confirmed thanks to the official ISTAT codelist (CL_ESITO), available at:
`https://esploradati.istat.it/SDMXWS/rest/codelist/IT1/CL_ESITO`

- **M** = "killed" — not male gender (as initially assumed)
- **F** = "injured" — not female gender (as initially assumed)
- **9** = "total"

This explains why:
- **KILLINJ** (killed and injured) only shows M and F, never 9 so the total number of injured and killed people must be calculated by summing F+M manually
- **ROADACC** (road accidents) only shows 9, since a road accident is a single event and doesn't split into killed/injured like KILLINJ does

In [393]:
#Dropping empty columns from istat_df (mostly metadata)
dropped_columns_istat_df = ['OBS_STATUS', 'NOTE_DS', 'NOTE_REF_AREA', 'NOTE_DATA_TYPE', 'NOTE_RESULT', 'NOTE_TIME_PERIOD', 'BASE_PER', 'UNIT_MEAS', 'UNIT_MULT']
istat_df = istat_df.drop(columns= dropped_columns_istat_df)
istat_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 573552 entries, 0 to 573551
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATAFLOW     573552 non-null  str
 1   FREQ         573552 non-null  str
 2   REF_AREA     573552 non-null  str
 3   DATA_TYPE    573552 non-null  str
 4   RESULT       573552 non-null  str
 5   TIME_PERIOD  573552 non-null  int64
 6   OBS_VALUE    573552 non-null  int64
dtypes: int64(2), str(5)
memory usage: 30.6 MB

In [394]:
# Checking DATAFLOW and FREQ unique values to confirm whether they add relevant informations
print(istat_df['DATAFLOW'].unique())
print(istat_df['FREQ'].unique())

<StringArray>
['IT1:41_983(1.0)']
Length: 1, dtype: str
<StringArray>
['A']
Length: 1, dtype: str

In [395]:
# Drop DATAFLOW and FREQ columns: both of them are constant across all rows and add no informations to the analysis
istat_df = istat_df.drop(columns=['DATAFLOW', 'FREQ'])
istat_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 573552 entries, 0 to 573551
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   REF_AREA     573552 non-null  str
 1   DATA_TYPE    573552 non-null  str
 2   RESULT       573552 non-null  str
 3   TIME_PERIOD  573552 non-null  int64
 4   OBS_VALUE    573552 non-null  int64
dtypes: int64(2), str(3)
memory usage: 21.9 MB

In [396]:
#Checking the unique values of situas_df's columns to confirm whether they add relevant info to the analysis
for col in ['Codice Ripartizione geografica', 'Codice Regione', 'Codice Provincia (Storico)', 'Comune (dizione straniera)', 'Sigla automobilistica', 'Capoluogo di Provincia/Uts', 'Capoluogo di Regione', 'Popolazione legale', 'Anno Censimento']:
    print(col)
    print(situas_df[col].unique())
    print()

Codice Ripartizione geografica
[1 2 3 4 5]

Codice Regione
[ 1  2  7  3  4  5  6  8 11  9 10 12 15 13 14 16 17 18 19 20]

Codice Provincia (Storico)
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 108 109 110 111]

Comune (dizione straniera)
<StringArray>
[                       nan,                   'Aldein',
                  'Andrian',                   'Altrei',
  'Eppan an der Weinstraße',                  'Hafling',
                    'Abtei',                  'Barbian',
                    'Bozen',                    'Prags',
 ...
                  'Sèn Jan',                 'Doberdob',
                'Števerjan',         'Sovodnje ob Soči',
          'Devin Nabrežina',               'Repentabor',
                   'Dolina',                   'Zgonik',
 'Salurn an der Weinstraße', 'Montan an der Weinstraße']
Length: 127, dtype: str

Sigla automobilistica
<StringArray>
['TO', 'VC', 'NO', 'CN', 'AT', 'AL', 'AO', 'IM', 'SV', 'GE',
 ...
 'LO', 'RN', 'PO', 'KR', 'VV', 'VB', 'MB', 'FM', 'BT', 'SU']
Length: 107, dtype: str

Capoluogo di Provincia/Uts
[0 1]

Capoluogo di Regione
[0 1]

Popolazione legale
[ 2644  3819   462 ... 13317  3705  5781]

Anno Censimento
[2011 2021]

In [397]:
#Dropping unnecessary situas's columns for the analysis
dropped_columns_situas_df = ['Codice Ripartizione geografica', 'Codice Regione', 'Codice Provincia (Storico)','Codice Provincia/Uts', 'Codice Comune (numerico)', 'Comune (dizione straniera)', 'Capoluogo di Provincia/Uts', 'Capoluogo di Regione', 'Popolazione legale', 'Anno Censimento']
situas_df = situas_df.drop(columns= dropped_columns_situas_df)
situas_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55375 entries, 0 to 55374
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Codice Comune (alfanumerico)  55375 non-null  str
 1   Comune                        55368 non-null  str
 2   Sigla automobilistica         54731 non-null  str
 3   Superficie (Kmq)              55375 non-null  float64
 4   Anno (Superficie)             55375 non-null  int64
 5   Popolazione residente         55375 non-null  int64
 6   Anno (Popolazione residente)  55375 non-null  int64
dtypes: float64(1), int64(3), str(3)
memory usage: 3.0 MB

In [398]:
#Pivot istat_df to one row per municipality/year, obtaining separate columns for accidents/killed/injured.
# Using sum as aggregation because OBS_VALUE is a count of people/events. Summing values preserves the actual total since each row contains one value.

istat_df_pivot = istat_df.pivot_table(
    index=['REF_AREA', 'TIME_PERIOD'],
    columns=['DATA_TYPE', 'RESULT'],
    values='OBS_VALUE',
    aggfunc='sum'
).reset_index()
istat_df_pivot.head(10)

DATA_TYPE REF_AREA TIME_PERIOD KILLINJ    ROADACC
RESULT                               F  M       9
0           001001        2001      10  0       5
1           001001        2002      10  0       5
2           001001        2003       7  0       4
3           001001        2004      13  0       9
4           001001        2005       2  0       2
5           001001        2006       1  0       1
6           001001        2007      12  0       8
7           001001        2008      10  0       5
8           001001        2009       7  0       4
9           001001        2010      14  0       7

In [399]:
#Checking columns order
istat_df_pivot.columns.tolist()

[('REF_AREA', ''),
 ('TIME_PERIOD', ''),
 ('KILLINJ', 'F'),
 ('KILLINJ', 'M'),
 ('ROADACC', '9')]

In [400]:
# Flatten and rename the two-level pivot columns 
istat_df_pivot.columns = ['REF_AREA', 'TIME_PERIOD', 'INJURED', 'KILLED', 'TOTAL_ACCIDENTS']
istat_df_pivot.head()

  REF_AREA  TIME_PERIOD  INJURED  KILLED  TOTAL_ACCIDENTS
0   001001         2001       10       0                5
1   001001         2002       10       0                5
2   001001         2003        7       0                4
3   001001         2004       13       0                9
4   001001         2005        2       0                2

In [401]:
# Joined istat_df_pivot with cleaned situas_df. Using two keys per df in order to avoid duplicates and misleading data.
# Using inner join since situas_df only covers 2018-2024: this naturally filters istat_df_pivot, leading to the year range selected for the analysis.
df = istat_df_pivot.merge(situas_df,
    left_on=['REF_AREA', 'TIME_PERIOD'],
    right_on=['Codice Comune (alfanumerico)', 'Anno (Popolazione residente)'],
    how='inner')
df.sample(5)

,REF_AREA,TIME_PERIOD,INJURED,KILLED,TOTAL_ACCIDENTS,Codice Comune (alfanumerico),Comune,Sigla automobilistica,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente)
5738,006014,2022,4,0,4,006014,Belforte Monferrato,AL,8.3258,2022,497,2022
42871,078089,2021,0,0,0,078089,Paludi,CS,41.7393,2021,1014,2021
41122,075056,2021,12,2,7,075056,Ortelle,LE,10.2252,2021,2234,2021
39373,070035,2019,0,0,0,070035,Macchia Valfortore,CB,26.7323,2019,517,2019
22180,026061,2023,5,0,3,026061,Possagno,TV,12.1102,2023,2294,2023

In [402]:
# Checking df shape
df.shape

(53817, 12)

In [403]:
# Checking whether the inner join filtered the year range correctly
df['TIME_PERIOD'].unique()

array([2018, 2019, 2020, 2021, 2022, 2023, 2024])

In [404]:
#Dropping redundant column after join.
#Renaming all columns to English for consistency
df = df.drop(columns= ['Codice Comune (alfanumerico)'])

df = df.rename(columns= {'Comune': 'MUNICIPALITY',
    'Sigla automobilistica': 'PROVINCE_CODE',
    'Superficie (Kmq)': 'SURFACE_KMQ',
    'Anno (Superficie)': 'SURFACE_YEAR',
    'Popolazione residente': 'POPULATION',
    'Anno (Popolazione residente)': 'POPULATION_YEAR'})
df.columns.tolist()

['REF_AREA',
 'TIME_PERIOD',
 'INJURED',
 'KILLED',
 'TOTAL_ACCIDENTS',
 'MUNICIPALITY',
 'PROVINCE_CODE',
 'SURFACE_KMQ',
 'SURFACE_YEAR',
 'POPULATION',
 'POPULATION_YEAR']